### ISSUE TITLE
Transparency issues and SSG crash

### ISSUE THREAD

**Issue by leillo1975** [IOBYTE/acclint#1]
Hi @IOBYTE 
I made a test with [my LongJour track](https://forge.a-lec.org/leillo1975/longjour) with this command:
`acclint --combineTexture longjour.ac -o longjour.new.ac`

It takes some time to finish, but the final results are overwhelming. Take a look to this screenshots after the first lap and compare the average fps. 
-Before:
![LongJourDefaultOSG](https://github.com/IOBYTE/acclint/assets/551821/c6b578a0-ffa2-4345-abe3-ddf2168e84ad)
-After:
![LongJourAcclintOSG-OK](https://github.com/IOBYTE/acclint/assets/551821/fdb09091-f241-4518-b27e-9f645b4cf8d6)

For the moment I only find two problems:
- First one is an issue with fences and trees. Take a look to the second screenshot to see the fences, and this other for the trees:
![LongJourAcclint_TreesBug](https://github.com/IOBYTE/acclint/assets/551821/0e140c19-9664-46ac-be91-1cfcfcc47e13)

Could it be that it is not using the "_n" in the texture name correctly for objects with transparency (treeX_n)?

- Second one, I went to check the track's performance in SSG, but upon loading it the game crashed to the Desktop with the following message:

```
00:00:12.775 Default  Info    Graphic options : Number of cloud layers : 1
00:00:12.779 Default  Error   Env. texture file shadow2.png not found in tracks/road/longjour;data/img;data/textures;.
00:00:12.779 Default  Error   Env. texture file shadow2.rgb not found in tracks/road/longjour;data/img;data/textures;.
00:00:12.779 Default  Warning shadow2.png/rgb not found ; no shadow mapping on cars for this track
00:00:12.779 Default  Info    Loading background-sky.ac
00:00:12.800 Default  Info    Loading longjour.new.ac
WARNING: Map is not a power-of-two in size!
corrupted double-linked list
Aborted (memory data was recovered)
```
Seems that acclint changes the size of the track

**Comment by IOBYTE** [comment]
I no longer combine transparent objects into single objects so they can still be depth sorted.  This should fix the transparency issue.

The other issues are speed dreams related and can't be fixed here.  I closing this issue.
