### ISSUE TITLE
acclint files with --combineTexture .acc file fails on Windows

### ISSUE THREAD

**Issue by leillo1975** [IOBYTE/acclint#2]
Hello

This morning June Ravenmoon (formerly harunasan) told me that when he tries to create a race with bots on [my longjour track](https://codeberg.org/leillo1975/longjour) on Windows with the ‘main’ version (not the current release), the game closes to the desktop.  I have tested it on a Windows partition (real, not virtual), and it does indeed fail.

But the failure occurs when after creating the .acc file with raceline in trackeditor, we use acclint with --combineTexture. If I create a race with the track as it comes out of trackeditor, it doesn't fail.

Cheers

**Comment by IOBYTE** [comment]
I just updated your track from git and it runs ok on linux with osg and ssg.  I can't test it on windows because I can't build speed dreams on windows anymore.

**Comment by leillo1975** [comment]
You are right, on Linux it works fine. You can use my portable package created 1 month ago (includes LongJour and Spa version from a month ago too, you need to download the latest version of the track to reproduce the problem):

https://drive.google.com/file/d/1pH7XziachYvMT6v33e_cbWgVIr26L0I2/view?usp=drive_link

**Comment by IOBYTE** [comment]
This is a speed dreams SSG problem.  It works fine on OSG.
